# NodeJS Version 16
FROM node:16.18-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Install Linux Package
RUN apt-get update && apt-get install -y \
    r-base \
  && rm -rf /var/lib/apt/lists/*

# Set Env
ENV NODE_ENV development
EXPOSE 3000

# Cmd script
CMD ["npm", "run", "dev"]
