# NodeJS Version 16
FROM node:16.18-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install --legacy-peer-deps

# Install Linux Package
RUN apt-get update && apt-get install -y \
    r-base \
    pandoc \
  && rm -rf /var/lib/apt/lists/*

RUN Rscript -e "install.packages('rmarkdown')"

# Set Env
ENV NODE_ENV production
EXPOSE 3000

# Cmd script
CMD ["npm", "run", "start"]
